# config.ini
[DEFAULT]
# Delivery Filters
min_delivery_quantity = 10000
min_percent_change = 0.0
min_delivery_times = 3.0

# Market Cap Filter
min_market_cap_cr = 500.0

# Market Cap Source (Options: 'screener', 'yfinance')
market_cap_source = yfinance

# Number of threads for fetching market cap data
market_cap_workers = 10

# Technical Indicators
rs_period = 55
rsi_period = 14

# System Defaults
days_back = 8
max_retries_today = 5
download_dir = raw_bhvdata
output_dir = ./output
cache_dir = ./cache
sqlite_db = bhavcopy.sqlite

# Telegram Configuration
telegram_bot_token = 7858805492:AAHBP21whW6KkmXu3a2LbC9yY84YKdK7Ur8
telegram_chat_id = 687480641

# Angel One API Configuration
angel_api_key = 8rZ2gieL
angel_username = A55231223
angel_pin = 2457
angel_totp_secret = 3MU5S3EHQLSLHJE6MZPLSSRYOI
benchmark_symbol = NIFTY 50
benchmark_token = 99926000

# Headers and Timeout
user_agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
timeout = 15